name: Debug QEMU/KVM Environment

on:
  push:
    branches:
      - main

jobs:
  debug-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List Files in /usr/lib/qemu/
      run: ls -l /usr/lib/qemu/

    - name: Show virbr0 Status
      run: ip link show virbr0 || true  # The 'true' at the end prevents the workflow from failing if the command returns an error

    - name: Restart libvirt Service
      run: |
        sudo systemctl restart libvirtd
        sleep 5  # Allow some time for services to restart
        sudo systemctl status libvirtd

    - name: Restart QEMU Service
      run: |
        sudo systemctl restart qemu-kvm
        sleep 5  # Allow some time for services to restart

    - name: Check qemu-bridge-helper
      run: ls -l /usr/lib/qemu/qemu-bridge-helper

    - name: Display AppArmor Status
      run: sudo apparmor_status || true  # Check AppArmor status, ignore errors

    - name: Display SELinux Status
      run: sestatus || true  # Check SELinux status, ignore errors

    - name: Show QEMU Logs
      run: cat /var/log/libvirt/qemu/*.log || true  # Display QEMU logs, ignore errors

    - name: Run QEMU Commands
      run: |
        qemu-img --version
        qemu-system-x86_64 --version

    - name: Check System Journal for Errors
      run: journalctl -xe || true  # Display system journal, ignore errors
