name: Run Ubuntu with Ngrok

on:
  push:
    branches:
      - main

jobs:
  build-vm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up QEMU/KVM
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-kvm

    - name: Create VM Disk
      run: |
        qemu-img create -f qcow2 ubuntu-vm.qcow2 20G

    - name: Start VM
      run: |
        qemu-system-x86_64 -drive file=ubuntu-vm.qcow2 -m 4G -enable-kvm -vga virtio -display vnc=:0

  expose-vm:
    runs-on: ubuntu-latest
    needs: build-vm
    steps:
    - name: Install Ngrok
      run: |
        sudo apt-get install -y unzip
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        sudo mv ngrok /usr/local/bin/ngrok

    - name: Start Ngrok
      run: |
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ./ngrok tcp 5900 > ngrok_url.txt &

    - name: Display Ngrok URL
      run: |
        sleep 10
        cat ngrok_url.txt
